### ISSUE TITLE
Allow selection of sequences for download by ticking checkboxes in browse/search view

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#2247]
This comes from our beta testers:

It would be nice to be able to checkbox-select sequences in the browse view to subset sequences for download.

Implementation wise, we could store the list of selected sequences in URL path, similar to how we allow filtering by accession. Just that in this case we only filter at the point of _download_ not as soon as the first accession is entered.

**Comment by fhennig** [comment]
Hey! So I just had a chat with @corneliusroemer about this and here's how I would approach this:

---

As a user I want to be able to select a few sequences that interest me and download them together.

## Acceptance Criteria

The Table in the Search UI contains a new column of checkboxes, which are by default all unchecked. Users can check boxes and then chose to only download selected sequences in the download dialog.
If no boxes are selected, everything is downloaded (as it is now).
If there is a selection, a label will say how many sequences are selected at the top of the table.
The selection is not cleared after downloading the sequences.

**optional:** There are unit tests.

### not in scope

- for now, the selection will be cleared if the filters are updated
- there is going to be a limit on how many sequences can be selected at once due to technical limitations
- E2E tests.

## Implementation

- Like other state, the checked sequences will be encoded in the URL, this also sets a limit on how many sequences can be selected as the string can only get so long.
- this way the selection can be treated like the other filter stuff
