### ISSUE TITLE
Deemphasize submitter on sequence details page

### ISSUE THREAD

**Issue by emmahodcroft** [loculus-project/loculus#2614]
After setting up a revision on behalf of another user, Curators become the submitter!

Version 1: 
![image](https://github.com/user-attachments/assets/6fdcaeb3-9ec5-4a01-99f7-a45bdc604480)

Version 2 (after curation):
![image](https://github.com/user-attachments/assets/855a9788-54e1-4f5a-af1f-ac633f201881)

This is not good, as the credit for the sequence should always stay with the original Submitter, not with curators who are helping out.

In this case, Curator set up the revision, but Submitter accepted it.

**Comment by chaoran-chen** [comment]
I'm not sure how this should be resolved. Technically, I think that it makes a lot of sense to store the user who performed the action and that is what the "submitter" field currently is. The "submitter" is not to be considered the owner as the owner is the group. But I can certainly see the issue here as this is a concept that is not common. A few ideas would be:

1. We rename the field to something else (e.g., "uploader"?).
2. We also show the field "Approver". Then, in combination with 1., we have `Uploader: emmahodcroft-curator, approver: <the actual submitter>`
3. We de-emphasize (or even now show at all) the field submitter but only the submitting group.
4. We introduce a field called "submitted_on_behalf_of" which is optional and will be filled when a curator uploads a sequence. On the website, this can be rendered to either `<submitter> on behalf of <submitted_on_behalf_of>` or `<submitted_on_behalf_of> (uploaded by <submitter>)`. The question, however, could be what someone should do if they upload really on behalf of the group and not on behalf of a single person in the group.

For inspiration, we could look at git where there is also a distinguishment between a committer and author.

**Comment by theosanderson** [comment]
> We de-emphasize (or even now show at all) the field submitter on the website but only the submitting group.

I was also thinking about this. I think we should do this in any case, and IMO it will solve the problem.

**Comment by chaoran-chen** [comment]
It does seem like an important issue, so I moved it to the Prio 1 milestone, hope that's ok!

**Comment by emmahodcroft** [comment]
I guess my worry would be - if I want to see all my sequences that I submitted it would make sense to me that I search submitter field for my username. Just because a curator helped me to fix a swapped date, It seems weird that sequence wouldn't show up like the others do?

I think we may need to think a bit about what people expect to see as 'submitter' (especially with lots of experience with databases where this will essentially never change) vs recording curations & edits later - to me I would picture and think of these these as two different things regardless of the technical similarity (which I acknowledge - though in future perhaps a curator can edit a date without need to 'resubmit' as such).

We should also maybe talk to sequence generators here. As a submitter I might be a bit miffed if I accepted Cornelius' help fixing a date and now his [curator] name is all over my sequences. Deemphasizing may help, but connotations of what a 'submitter' is may persist and may not match how we're using the term currently.

**Comment by theosanderson** [comment]
As Chaoran says, at one end of the spectrum we could completely remove the display of the account that submitted our sequence, and the ability to search by them. As I understand it our concept here is that credit really should be about the group. The person/account (even from that group) that happens to submit shouldn't really get elevated status. I agree atm, we give that which is a mistake. I think we should de-emphasise it to the extent of making it a little thing that appears in an pop up info box after clicking "technical details" or something - or possibly even making it only visible to group members. The internals of group dynamics of who submitted what doesn't really need to be public - it is something that group members will need to know.

**Comment by theosanderson** [comment]
Our accounts each have a person's name associated with them (though we don't at present make those names public, we may intend to). I can imagine that some organisations might not want sequences to have to be associated publicly with an individuals name (e.g. to protect the individual from strange internet people).

**Comment by emmahodcroft** [comment]
Ok fair, I'm happy to move in the direction where we really de-emphasize submitter. We may not need to remove it from search entirely (could still be useful,, even for curators for past things they've curated), but we could remove it from the 'default' search and put it somewhere down at the bottom of the list (or whatever), and really make it small/less visible on metadata view. 

Probably good to do this sooner-ish (in relative terms) so users learn not to rely on it from day 1

**Comment by corneliusroemer** [comment]
>  credit really should be about the group

Actually we have _authors_ and _author affiliation_ fields for that, the groups and user accounts are technical accounts only - at least that's how we've implemented things for now. Users and groups are relevant for audit log and editing rights - looking at it like that makes it obvious that they should be de-emphasized, and authors & affiliations should receive more emphasis.

Another way to show that submitter/groups are technicalities-only to be deemphasized is that for ingested sequence (the vast majority for now) group and submitter have nothing to do with the actual authors and their research groups.

**Comment by theosanderson** [comment]
I see what you are saying - and don't disagree - but as I understand it SeqSets will initially show group impact so it's a bit of both.

**Comment by corneliusroemer** [comment]
For seqsets to work properly then, we need to make them work with ingest submitted sequences and not rely on groups eventually.

**Comment by emmahodcroft** [comment]
I disagree about deemphasising groups. Groups are key to ownership of sequences, and are a big part of what we ourselves have emphasised when talking about Pathoplexus, and I think that this isn't so incorrect for having an idea of someone who's responsible for these sequences & involved in them. 

TBH if we didn't have the submitter thing with the curators I would say similarly about `submitter` and do think the average user is going to interpret it that way, but am willing to let this go to a more technical definition to mostly make curation easier.

**Comment by theosanderson** [comment]
Yeah, we should have nice public group pages showing group sequences in time

**Comment by corneliusroemer** [comment]
Groups confer editing rights, and they are important because we allow sharing of editing rights among multiple users.

Why do we have an author affiliation field if you're saying that groups are what matters? If you want to emphasize groups, then we need to create pseudo groups for ingested sequences, as for these attribution should be as important.

The current implementation means submitter and group are technical entities for submission related ownership purposes and metadata fields authors and affiliations are entities relevant for attribution and intellectual ownership.

Authors that end up in INSDC are from metadata, not from submitter.

**Comment by theosanderson** [comment]
I think they both matter. Maybe let's keep this issue for submitter's and migrate a group conversation over to Slack?

**Comment by emmahodcroft** [comment]
Technical entities can also be important. Though I agree that due to our definitions the submitter is confusing and thus should be de-emphasized, I don't see a reason to do this for groups, and indeed, think groups are important. They will often overlap with author lists but signify another type of (technical) responsibility and relationship.

Agree that to simplify discussion there's unified opinion about deemphasising `submitter` so we should scope this and move on this, and move groups discussion elsewhere, which is also a much more complicated topic.

**Comment by emmahodcroft** [comment]
At the Dev meeting on 21 Oct, the proposed solution agreed up on was to display (if appropriate) `submitter` and `original submitter` and `submission date` and `original submission date`. 

This would require:
- update on the backend to store these accessibly in two new fields (for 'original_`)
- update on the submission page view to check if `original_` is same as the 'usual' field, and if so, only display one. If not, display both.

Thoughts on this approach welcome!

**Comment by chaoran-chen** [comment]
Is the display of the original submitter and submission date only/mostly important for the display on the website or also important for the downloaded data? If it would be the first, we wouldn't need the backend changes. Regarding the second, the redundancy obviously isn't very nice but since the default download only fetches the latest versions and not older data, I can see the advantage of having the `original_` fields.

Should we also introduce original released date?

**Comment by corneliusroemer** [comment]
I'm strongly for include in downloaded data, end users want data to be denormalized, we already have a hundred columns, adding 2 is no problem.

Alternatives to `original` are `first` or `initial` rather than `original`?

**Comment by corneliusroemer** [comment]
In addition to visual changes and including original date, we should deemphasize the submission card by reordering the headings/cards (this is something that @theosanderson and I have had mentally in our backlog)

**Comment by emmahodcroft** [comment]
@corneliusroemer this is covered in issue: https://github.com/loculus-project/loculus/issues/3027

**Comment by emmahodcroft** [comment]
Current proposal: drop `submitter` from the detail view only until we can rework the details page overall as per #3027
