### ISSUE TITLE
feat(webpage, revision): Add an edit button to sequences that a user can revise

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#3092]
When users submit sequences - prior to approval - they can review the metadata and sequence that they uploaded via the webpage: 
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/329d284b-088b-4e38-9537-660d198daba7">
In this view users can update and revise the data that they uploaded. 

We should add an edit button for each sequence that a user is allowed to revise that allows users to go back to this view. Button could be added here:
<img width="526" alt="Screenshot 2024-10-28 at 18 03 18" src="https://github.com/user-attachments/assets/b36982c2-dfe5-4305-8ac3-e371ca62e8a4">

The view should be populated with the current metadata fields (we need original and processed metadata for this), users should be able to edit the fields and then approve their changes - creating a new version of the sequence.

**Comment by theosanderson** [comment]
https://github.com/loculus-project/loculus/issues/3030 is a less well-specced version of this issue

**Comment by theosanderson** [comment]
> the current metadata fields (we need original and processed metadata for this)

Do you have an idea for how we would use processed metadata here

**Comment by theosanderson** [comment]
Something to think about during this implementation:
IMO the review page edit button should be changed to open the edit page in a modal rather than as its own page. (This is something we always planned but deprioritised). We don't have to do this now but when we are genericising the edit component it may make sense to make it a react component if it is not already to allow this.
